const lessonLevels = {
    // DERS 1: KOŞULLU DURUMLAR
    1: {
        1: `<xml><block type="text_print" x="50" y="50"><value name="TEXT"><block type="text"><field name="TEXT">Sınav Sistemi Başladı</field></block></value></block></xml>`,
        2: `<xml><variables><variable id="puan">Puan</variable></variables><block type="variables_set" x="50" y="50"><field name="VAR" id="puan">Puan</field><value name="VALUE"><block type="math_number"><field name="NUM">60</field></block></value><next><block type="text_print"><value name="TEXT"><block type="variables_get"><field name="VAR" id="puan">Puan</field></block></value></block></next></block></xml>`,
        3: `<xml><variables><variable id="puan">Puan</variable></variables><block type="variables_set" x="50" y="50"><field name="VAR" id="puan">Puan</field><value name="VALUE"><block type="math_random_int"><value name="FROM"><shadow type="math_number"><field name="NUM">1</field></shadow></value><value name="TO"><shadow type="math_number"><field name="NUM">100</field></shadow></value></block></value><next><block type="controls_if"><value name="IF0"><block type="logic_compare"><field name="OP">GT</field><value name="A"><block type="variables_get"><field name="VAR" id="puan">Puan</field></block></value><value name="B"><block type="math_number"><field name="NUM">50</field></block></value></block></value><statement name="DO0"><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Geçtin!</field></block></value></block></statement></block></next></block></xml>`,
        4: `<xml><variables><variable id="puan">Puan</variable></variables><block type="variables_set" x="50" y="50"><field name="VAR" id="puan">Puan</field><value name="VALUE"><block type="math_random_int"><value name="FROM"><shadow type="math_number"><field name="NUM">1</field></shadow></value><value name="TO"><shadow type="math_number"><field name="NUM">100</field></shadow></value></block></value><next><block type="controls_if"><mutation else="1"></mutation><value name="IF0"><block type="logic_compare"><field name="OP">GT</field><value name="A"><block type="variables_get"><field name="VAR" id="puan">Puan</field></block></value><value name="B"><block type="math_number"><field name="NUM">50</field></block></value></block></value><statement name="DO0"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Harika, geçtin!</field></block></value></block></statement><statement name="ELSE"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Maalesef kaldın.</field></block></value></block></statement></block></next></block></xml>`,
        5: `<xml><variables><variable id="puan">Puan</variable></variables><block type="variables_set" x="50" y="50"><field name="VAR" id="puan">Puan</field><value name="VALUE"><block type="math_random_int"><value name="FROM"><shadow type="math_number"><field name="NUM">1</field></shadow></value><value name="TO"><shadow type="math_number"><field name="NUM">100</field></shadow></value></block></value><next><block type="text_print"><value name="TEXT"><block type="text_join"><mutation items="2"></mutation><value name="ADD0"><block type="text"><field name="TEXT">Aldığın Puan: </field></block></value><value name="ADD1"><block type="variables_get"><field name="VAR" id="puan">Puan</field></block></value></block></value><next><block type="controls_if"><mutation else="1"></mutation><value name="IF0"><block type="logic_compare"><field name="OP">GT</field><value name="A"><block type="variables_get"><field name="VAR" id="puan">Puan</field></block></value><value name="B"><block type="math_number"><field name="NUM">50</field></block></value></block></value><statement name="DO0"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Tebrikler, geçtin!</field></block></value><next><block type="ai_arkaplan_renk"><field name="COLOR">green</field></block></next></block></statement><statement name="ELSE"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Maalesef kaldın.</field></block></value><next><block type="ai_arkaplan_renk"><field name="COLOR">red</field></block></next></block></statement></block></next></block></next></block></xml>`
    },
    // DERS 2: DÖNGÜLER
    2: {
        1: `<xml><block type="text_print" x="50" y="50"><value name="TEXT"><block type="text"><field name="TEXT">Merhaba Robot</field></block></value></block></xml>`,
        2: `<xml><block type="controls_repeat_ext" x="50" y="50"><value name="TIMES"><block type="math_number"><field name="NUM">3</field></block></value><statement name="DO"><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Merhaba Robot</field></block></value></block></statement></block></xml>`,
        3: `<xml><block type="controls_repeat_ext" x="50" y="50"><value name="TIMES"><block type="math_number"><field name="NUM">3</field></block></value><statement name="DO"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Geri sayım</field></block></value><next><block type="ai_bekle"><field name="SECONDS">1</field></block></next></block></statement></block></xml>`,
        4: `<xml><variables><variable id="sayac">GeriSayım</variable></variables><block type="variables_set" x="50" y="50"><field name="VAR" id="sayac">GeriSayım</field><value name="VALUE"><block type="math_number"><field name="NUM">5</field></block></value><next><block type="controls_repeat_ext"><value name="TIMES"><block type="math_number"><field name="NUM">5</field></block></value><statement name="DO"><block type="ai_metni_seslendir"><value name="TEXT"><block type="variables_get"><field name="VAR" id="sayac">GeriSayım</field></block></value><next><block type="variables_set"><field name="VAR" id="sayac">GeriSayım</field><value name="VALUE"><block type="math_arithmetic"><field name="OP">MINUS</field><value name="A"><block type="variables_get"><field name="VAR" id="sayac">GeriSayım</field></block></value><value name="B"><block type="math_number"><field name="NUM">1</field></block></value></block></value><next><block type="ai_bekle"><field name="SECONDS">1</field></block></next></block></next></block></statement></block></next></block></xml>`,
        5: `<xml><variables><variable id="sayac">GeriSayım</variable></variables><block type="variables_set" x="50" y="50"><field name="VAR" id="sayac">GeriSayım</field><value name="VALUE"><block type="math_number"><field name="NUM">5</field></block></value><next><block type="controls_repeat_ext"><value name="TIMES"><block type="math_number"><field name="NUM">5</field></block></value><statement name="DO"><block type="ai_metni_seslendir"><value name="TEXT"><block type="variables_get"><field name="VAR" id="sayac">GeriSayım</field></block></value><next><block type="variables_set"><field name="VAR" id="sayac">GeriSayım</field><value name="VALUE"><block type="math_arithmetic"><field name="OP">MINUS</field><value name="A"><block type="variables_get"><field name="VAR" id="sayac">GeriSayım</field></block></value><value name="B"><block type="math_number"><field name="NUM">1</field></block></value></block></value><next><block type="ai_bekle"><field name="SECONDS">1</field></block></next></block></next></block></statement><next><block type="ai_arkaplan_renk"><field name="COLOR">red</field><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Ateş!</field></block></value></block></next></block></next></block></next></block></xml>`
    },
    // DERS 3: KAMERA VE PİKSEL
    3: {
        1: `<xml><block type="ai_kamera_ac" x="50" y="50"></block></xml>`,
        2: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_bekle"><field name="SECONDS">3</field><next><block type="ai_kamera_kapat"></block></next></block></next></block></xml>`,
        3: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Kamera açıldı</field></block></value><next><block type="ai_bekle"><field name="SECONDS">3</field><next><block type="ai_kamera_kapat"><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Kamera kapandı</field></block></value></block></next></block></next></block></next></block></next></block></xml>`,
        4: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="controls_repeat_ext"><value name="TIMES"><block type="math_number"><field name="NUM">3</field></block></value><statement name="DO"><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Kayıt...</field></block></value><next><block type="ai_bekle"><field name="SECONDS">1</field></block></next></block></statement><next><block type="ai_kamera_kapat"></block></next></block></next></block></xml>`,
        5: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Güvenlik kamerası devrede. 5 saniye kayıt yapılacak.</field></block></value><next><block type="controls_repeat_ext"><value name="TIMES"><block type="math_number"><field name="NUM">5</field></block></value><statement name="DO"><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Kayıt alınıyor...</field></block></value><next><block type="ai_bekle"><field name="SECONDS">1</field></block></next></block></statement><next><block type="ai_kamera_kapat"><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Kamera kapatıldı. Teşekkürler.</field></block></value></block></next></block></next></block></next></block></next></block></xml>`
    },
    // DERS 4: RENK FİLTRELEME
    4: {
        1: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_renk_filtresi"><field name="COLOR">red</field></block></next></block></xml>`,
        2: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="controls_repeat_ext"><value name="TIMES"><block type="math_number"><field name="NUM">3</field></block></value><statement name="DO"><block type="ai_renk_filtresi"><field name="COLOR">red</field><next><block type="ai_bekle"><field name="SECONDS">1</field><next><block type="ai_renk_filtresi"><field name="COLOR">none</field><next><block type="ai_bekle"><field name="SECONDS">1</field></block></next></block></next></block></next></block></statement></block></next></block></xml>`,
        3: `<xml><variables><variable id="komut">Komut</variable></variables><block type="ai_kamera_ac" x="50" y="50"><next><block type="variables_set"><field name="VAR" id="komut">Komut</field><value name="VALUE"><block type="ai_ses_dinle"></block></value><next><block type="controls_if"><value name="IF0"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Komut</field></block></value><value name="B"><block type="text"><field name="TEXT">kırmızı</field></block></value></block></value><statement name="DO0"><block type="ai_renk_filtresi"><field name="COLOR">red</field></block></statement></block></next></block></next></block></xml>`,
        4: `<xml><variables><variable id="komut">Komut</variable></variables><block type="ai_kamera_ac" x="50" y="50"><next><block type="controls_whileUntil"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="komut">Komut</field><value name="VALUE"><block type="ai_ses_dinle"></block></value><next><block type="controls_if"><value name="IF0"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Komut</field></block></value><value name="B"><block type="text"><field name="TEXT">kırmızı</field></block></value></block></value><statement name="DO0"><block type="ai_renk_filtresi"><field name="COLOR">red</field></block></statement></block></next></block></statement></block></next></block></xml>`,
        5: `<xml><variables><variable id="komut">Komut</variable></variables><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Renk asistanı hazır. Kırmızı veya Mavi deyin.</field></block></value><next><block type="controls_whileUntil"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="komut">Komut</field><value name="VALUE"><block type="ai_ses_dinle"></block></value><next><block type="controls_if"><mutation elseif="1" else="1"></mutation><value name="IF0"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Komut</field></block></value><value name="B"><block type="text"><field name="TEXT">kırmızı</field></block></value></block></value><statement name="DO0"><block type="ai_renk_filtresi"><field name="COLOR">red</field><next><block type="ai_arkaplan_renk"><field name="COLOR">red</field></block></next></block></statement><value name="IF1"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Komut</field></block></value><value name="B"><block type="text"><field name="TEXT">mavi</field></block></value></block></value><statement name="DO1"><block type="ai_renk_filtresi"><field name="COLOR">blue</field><next><block type="ai_arkaplan_renk"><field name="COLOR">blue</field></block></next></block></statement><statement name="ELSE"><block type="ai_renk_filtresi"><field name="COLOR">none</field><next><block type="ai_arkaplan_renk"><field name="COLOR">black</field></block></next></block></statement></block></next></block></statement></block></next></block></next></block></xml>`
    },
    // DERS 5: YÜZ TAKİBİ
    5: {
        1: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_yuz_tespit_et"></block></next></block></xml>`,
        2: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Yüz tespit başlatılıyor</field></block></value><next><block type="ai_yuz_tespit_et"></block></next></block></next></block></xml>`,
        3: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_yuz_tespit_et"><next><block type="controls_whileUntil"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Yüzler taranıyor...</field></block></value><next><block type="ai_bekle"><field name="SECONDS">1</field></block></next></block></statement></block></next></block></next></block></xml>`,
        4: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_yuz_tespit_et"><next><block type="ai_bekle"><field name="SECONDS">3</field><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Sisteme hoş geldiniz.</field></block></value></block></next></block></next></block></next></block></xml>`,
        5: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Güvenlik kamerası devrede.</field></block></value><next><block type="ai_yuz_tespit_et"><next><block type="ai_bekle"><field name="SECONDS">3</field><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Yüzünüz doğrulandı, hoş geldiniz.</field></block></value><next><block type="ai_arkaplan_renk"><field name="COLOR">green</field></block></next></block></next></block></next></block></next></block></next></block></xml>`
    },
    // DERS 6: EL HAREKETİ
    6: {
        1: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"></block></next></block></xml>`,
        2: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"><next><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Eller aranıyor...</field></block></value></block></next></block></next></block></xml>`,
        3: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"><next><block type="controls_whileUntil"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Sanal fare aktif</field></block></value><next><block type="ai_bekle"><field name="SECONDS">1</field></block></next></block></statement></block></next></block></next></block></xml>`,
        4: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"><next><block type="ai_bekle"><field name="SECONDS">3</field><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Elleriniz göründü, kontrol sizde.</field></block></value></block></next></block></next></block></next></block></xml>`,
        5: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Sanal fare başlatıldı. Hareketlerinizi izliyorum.</field></block></value><next><block type="controls_whileUntil"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Eklemler taranıyor...</field></block></value><next><block type="ai_bekle"><field name="SECONDS">2</field></block></next></block></statement></block></next></block></next></block></next></block></xml>`
    },
    // DERS 7: METİNDEN SESE
    7: {
        1: `<xml><block type="ai_metni_seslendir" x="50" y="50"><value name="TEXT"><block type="text"><field name="TEXT">Merhaba Robot</field></block></value></block></xml>`,
        2: `<xml><block type="ai_metni_seslendir" x="50" y="50"><value name="TEXT"><block type="text_join"><mutation items="2"></mutation><value name="ADD0"><block type="text"><field name="TEXT">Merhaba </field></block></value><value name="ADD1"><block type="text"><field name="TEXT">Ahmet</field></block></value></block></value></block></xml>`,
        3: `<xml><block type="ai_metni_seslendir" x="50" y="50"><value name="TEXT"><block type="text_join"><mutation items="2"></mutation><value name="ADD0"><block type="text"><field name="TEXT">Şanslı sayın: </field></block></value><value name="ADD1"><block type="math_random_int"><value name="FROM"><shadow type="math_number"><field name="NUM">1</field></shadow></value><value name="TO"><shadow type="math_number"><field name="NUM">100</field></shadow></value></block></value></block></value></block></xml>`,
        4: `<xml><variables><variable id="isim">Isim</variable></variables><block type="variables_set" x="50" y="50"><field name="VAR" id="isim">Isim</field><value name="VALUE"><block type="text"><field name="TEXT">Ali</field></block></value><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text_join"><mutation items="2"></mutation><value name="ADD0"><block type="text"><field name="TEXT">Hoş geldin </field></block></value><value name="ADD1"><block type="variables_get"><field name="VAR" id="isim">Isim</field></block></value></block></value></block></next></block></xml>`,
        5: `<xml><variables><variable id="isim">MisafirAdı</variable></variables><block type="variables_set" x="50" y="50"><field name="VAR" id="isim">MisafirAdı</field><value name="VALUE"><block type="text"><field name="TEXT">Mühendis Bey</field></block></value><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text_join"><mutation items="2"></mutation><value name="ADD0"><block type="text"><field name="TEXT">Yapay Zeka Laboratuvarına hoş geldin, </field></block></value><value name="ADD1"><block type="variables_get"><field name="VAR" id="isim">MisafirAdı</field></block></value></block></value><next><block type="ai_bekle"><field name="SECONDS">3</field><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Seninle kodlamak çok eğlenceli olacak.</field></block></value></block></next></block></next></block></next></block></xml>`
    },
    // DERS 8: SES TANIMA
    8: {
        1: `<xml><block type="text_print" x="50" y="50"><value name="TEXT"><block type="ai_ses_dinle"></block></value></block></xml>`,
        2: `<xml><block type="controls_whileUntil" x="50" y="50"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="text_print"><value name="TEXT"><block type="ai_ses_dinle"></block></value><next><block type="ai_bekle"><field name="SECONDS">1</field></block></next></block></statement></block></xml>`,
        3: `<xml><variables><variable id="duyulan">Duyulan</variable></variables><block type="controls_whileUntil" x="50" y="50"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="duyulan">Duyulan</field><value name="VALUE"><block type="ai_ses_dinle"></block></value><next><block type="controls_if"><value name="IF0"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="duyulan">Duyulan</field></block></value><value name="B"><block type="text"><field name="TEXT">merhaba</field></block></value></block></value><statement name="DO0"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Sana da merhaba!</field></block></value></block></statement></block></next></block></statement></block></xml>`,
        4: `<xml><variables><variable id="duyulan">Duyulan</variable></variables><block type="controls_whileUntil" x="50" y="50"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="duyulan">Duyulan</field><value name="VALUE"><block type="ai_ses_dinle"></block></value><next><block type="controls_if"><mutation else="1"></mutation><value name="IF0"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="duyulan">Duyulan</field></block></value><value name="B"><block type="text"><field name="TEXT">merhaba</field></block></value></block></value><statement name="DO0"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Sana da merhaba!</field></block></value></block></statement><statement name="ELSE"><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Dediğini anlamadım.</field></block></value></block></statement></block></next></block></statement></block></xml>`,
        5: `<xml><variables><variable id="duyulan">Duyulan</variable></variables><block type="controls_whileUntil" x="50" y="50"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="duyulan">Duyulan</field><value name="VALUE"><block type="ai_ses_dinle"></block></value><next><block type="controls_if"><mutation elseif="2" else="1"></mutation><value name="IF0"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="duyulan">Duyulan</field></block></value><value name="B"><block type="text"><field name="TEXT">merhaba</field></block></value></block></value><statement name="DO0"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Sana da merhaba dostum!</field></block></value></block></statement><value name="IF1"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="duyulan">Duyulan</field></block></value><value name="B"><block type="text"><field name="TEXT">nasılsın</field></block></value></block></value><statement name="DO1"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Ben bir bilgisayarım, hep harikayım!</field></block></value></block></statement><value name="IF2"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="duyulan">Duyulan</field></block></value><value name="B"><block type="text"><field name="TEXT">kapat</field></block></value></block></value><statement name="DO2"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Sistem kapatılıyor.</field></block></value><next><block type="controls_flow_statements"><field name="FLOW">BREAK</field></block></next></block></statement><statement name="ELSE"><block type="text_print"><value name="TEXT"><block type="text_join"><mutation items="2"></mutation><value name="ADD0"><block type="text"><field name="TEXT">Şunu dedin: </field></block></value><value name="ADD1"><block type="variables_get"><field name="VAR" id="duyulan">Duyulan</field></block></value></block></value></block></statement></block></next></block></statement></block></xml>`
    },
    // DERS 9: MAKİNE ÖĞRENMESİ
    9: {
        1: `<xml><block type="text_print" x="50" y="50"><value name="TEXT"><block type="text"><field name="TEXT">Eğitim Başlıyor</field></block></value></block></xml>`,
        2: `<xml><block type="controls_repeat_ext" x="50" y="50"><value name="TIMES"><block type="math_number"><field name="NUM">10</field></block></value><statement name="DO"><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Veri Okundu!</field></block></value></block></statement></block></xml>`,
        3: `<xml><block type="controls_repeat_ext" x="50" y="50"><value name="TIMES"><block type="math_number"><field name="NUM">10</field></block></value><statement name="DO"><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Öğreniliyor...</field></block></value></block></statement><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Öğrenme tamamlandı.</field></block></value></block></next></block></xml>`,
        4: `<xml><block type="text_print" x="50" y="50"><value name="TEXT"><block type="text"><field name="TEXT">Köpek Eğitimi</field></block></value><next><block type="controls_repeat_ext"><value name="TIMES"><block type="math_number"><field name="NUM">5</field></block></value><statement name="DO"><block type="ai_bekle"><field name="SECONDS">1</field><next><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Ödül verildi!</field></block></value></block></next></block></statement></block></next></block></xml>`,
        5: `<xml><block type="text_print" x="50" y="50"><value name="TEXT"><block type="text"><field name="TEXT">Robotik Köpek Eğitimi Başlıyor!</field></block></value><next><block type="controls_repeat_ext"><value name="TIMES"><block type="math_number"><field name="NUM">5</field></block></value><statement name="DO"><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Oturmayı öğreniyor... Ödül verildi!</field></block></value><next><block type="ai_bekle"><field name="SECONDS">1</field></block></next></block></statement><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Köpeğiniz artık komutlarınızı tamamen öğrendi!</field></block></value></block></next></block></next></block></xml>`
    },
    // DERS 10: SOHBET BOTU (CHATBOT)
    10: {
        1: `<xml><block type="ai_metni_seslendir" x="50" y="50"><value name="TEXT"><block type="text"><field name="TEXT">Merhaba, ben bir sohbet botuyum!</field></block></value></block></xml>`,
        2: `<xml><block type="text_print" x="50" y="50"><value name="TEXT"><block type="ai_ses_dinle"></block></value></block></xml>`,
        3: `<xml><variables><variable id="komut">Söylenen</variable></variables><block type="controls_whileUntil" x="50" y="50"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="komut">Söylenen</field><value name="VALUE"><block type="ai_ses_dinle"></block></value><next><block type="controls_if"><value name="IF0"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Söylenen</field></block></value><value name="B"><block type="text"><field name="TEXT">nasılsın</field></block></value></block></value><statement name="DO0"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Harikayım, teşekkürler!</field></block></value></block></statement></block></next></block></statement></block></xml>`,
        4: `<xml><variables><variable id="komut">Söylenen</variable></variables><block type="controls_whileUntil" x="50" y="50"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="komut">Söylenen</field><value name="VALUE"><block type="ai_ses_dinle"></block></value><next><block type="controls_if"><mutation elseif="1" else="1"></mutation><value name="IF0"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Söylenen</field></block></value><value name="B"><block type="text"><field name="TEXT">merhaba</field></block></value></block></value><statement name="DO0"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Sana da merhaba!</field></block></value></block></statement><value name="IF1"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Söylenen</field></block></value><value name="B"><block type="text"><field name="TEXT">adın ne</field></block></value></block></value><statement name="DO1"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Benim adım Asistan Bot.</field></block></value></block></statement><statement name="ELSE"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Bunu anlayamadım.</field></block></value></block></statement></block></next></block></statement></block></xml>`,
        5: `<xml><variables><variable id="komut">Söylenen</variable></variables><block type="ai_metni_seslendir" x="50" y="50"><value name="TEXT"><block type="text"><field name="TEXT">Sohbet botu aktif. Sizi dinliyorum.</field></block></value><next><block type="controls_whileUntil"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="komut">Söylenen</field><value name="VALUE"><block type="ai_ses_dinle"></block></value><next><block type="controls_if"><mutation elseif="2" else="1"></mutation><value name="IF0"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Söylenen</field></block></value><value name="B"><block type="text"><field name="TEXT">nasılsın</field></block></value></block></value><statement name="DO0"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Bir yapay zeka olarak her zaman formdayım.</field></block></value><next><block type="ai_arkaplan_renk"><field name="COLOR">blue</field></block></next></block></statement><value name="IF1"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Söylenen</field></block></value><value name="B"><block type="text"><field name="TEXT">teşekkürler</field></block></value></block></value><statement name="DO1"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Rica ederim, görevim bu.</field></block></value><next><block type="ai_arkaplan_renk"><field name="COLOR">green</field></block></next></block></statement><value name="IF2"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Söylenen</field></block></value><value name="B"><block type="text"><field name="TEXT">görüşürüz</field></block></value></block></value><statement name="DO2"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Hoşçakalın!</field></block></value><next><block type="ai_arkaplan_renk"><field name="COLOR">black</field><next><block type="controls_flow_statements"><field name="FLOW">BREAK</field></block></next></block></next></block></statement><statement name="ELSE"><block type="text_print"><value name="TEXT"><block type="text_join"><mutation items="2"></mutation><value name="ADD0"><block type="text"><field name="TEXT">Şunu dediniz: </field></block></value><value name="ADD1"><block type="variables_get"><field name="VAR" id="komut">Söylenen</field></block></value></block></value></block></statement></block></next></block></statement></block></next></block></xml>`
    },
    // DERS 11: EL HAREKETLERİ İLE FARE KONTROLÜ
    11: {
        1: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"></block></next></block></xml>`,
        2: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"><next><block type="ai_sanal_imlec_ac"></block></next></block></next></block></xml>`,
        3: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Sanal fare aktif ediliyor.</field></block></value><next><block type="ai_sanal_imlec_ac"></block></next></block></next></block></next></block></xml>`,
        4: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">İşaret parmağınızı havaya kaldırarak fareyi yönlendirin.</field></block></value><next><block type="ai_el_tespit_et"><next><block type="ai_sanal_imlec_ac"></block></next></block></next></block></next></block></xml>`,
        5: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Harika! Artık bilgisayarı bir sihirbaz gibi sadece el hareketlerinizle kontrol edebilirsiniz.</field></block></value><next><block type="ai_el_tespit_et"><next><block type="ai_sanal_imlec_ac"><next><block type="ai_bekle"><field name="SECONDS">2</field><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Denemek için elinizi kameraya doğru sallayın!</field></block></value></block></next></block></next></block></next></block></next></block></next></block></xml>`
    },
    // DERS 12: EL İLE BLOK KONTROLÜ
    12: {
        1: `<xml><block type="ai_sanal_imlec_ac" x="50" y="50"></block></xml>`,
        2: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"><next><block type="ai_sanal_imlec_ac"></block></next></block></next></block></xml>`,
        3: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"><next><block type="ai_sanal_imlec_ac"><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Tıklamak için iki parmağınızı birleştirin.</field></block></value></block></next></block></next></block></next></block></xml>`,
        4: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"><next><block type="ai_sanal_imlec_ac"><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Blokları havadan tutarak sürükleyebilirsiniz.</field></block></value></block></next></block></next></block></next></block></xml>`,
        5: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"><next><block type="ai_sanal_imlec_ac"><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Tebrikler! İşaret ve baş parmağınızı birleştirerek ekrandaki tüm blokları tutabilir, havadan sürükleyerek yerlerini değiştirebilirsiniz.</field></block></value><next><block type="ai_bekle"><field name="SECONDS">5</field><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Geleceğin teknolojisini şu an yaşıyorsunuz!</field></block></value></block></next></block></next></block></next></block></next></block></next></block></xml>`
    },
    // DERS 13: SES İLE FARE YÖNLENDİRME
    13: {
        1: `<xml><variables><variable id="komut">Ses</variable></variables><block type="controls_whileUntil" x="50" y="50"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="komut">Ses</field><value name="VALUE"><block type="ai_ses_dinle"></block></value></block></statement></block></xml>`,
        2: `<xml><variables><variable id="komut">Ses</variable></variables><block type="ai_sanal_imlec_ac" x="50" y="50"><next><block type="controls_whileUntil"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="komut">Ses</field><value name="VALUE"><block type="ai_ses_dinle"></block></value><next><block type="controls_if"><value name="IF0"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Ses</field></block></value><value name="B"><block type="text"><field name="TEXT">yukarı</field></block></value></block></value><statement name="DO0"><block type="ai_sanal_imlec_sesle"><field name="YON">yukarı</field></block></statement></block></next></block></statement></block></next></block></xml>`,
        3: `<xml><variables><variable id="komut">Ses</variable></variables><block type="ai_sanal_imlec_ac" x="50" y="50"><next><block type="controls_whileUntil"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="komut">Ses</field><value name="VALUE"><block type="ai_ses_dinle"></block></value><next><block type="controls_if"><mutation elseif="1"></mutation><value name="IF0"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Ses</field></block></value><value name="B"><block type="text"><field name="TEXT">yukarı</field></block></value></block></value><statement name="DO0"><block type="ai_sanal_imlec_sesle"><field name="YON">yukarı</field></block></statement><value name="IF1"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Ses</field></block></value><value name="B"><block type="text"><field name="TEXT">aşağı</field></block></value></block></value><statement name="DO1"><block type="ai_sanal_imlec_sesle"><field name="YON">aşağı</field></block></statement></block></next></block></statement></block></next></block></xml>`,
        4: `<xml><variables><variable id="komut">Ses</variable></variables><block type="ai_sanal_imlec_ac" x="50" y="50"><next><block type="controls_whileUntil"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="komut">Ses</field><value name="VALUE"><block type="ai_ses_dinle"></block></value><next><block type="controls_if"><mutation elseif="3"></mutation><value name="IF0"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Ses</field></block></value><value name="B"><block type="text"><field name="TEXT">yukarı</field></block></value></block></value><statement name="DO0"><block type="ai_sanal_imlec_sesle"><field name="YON">yukarı</field></block></statement><value name="IF1"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Ses</field></block></value><value name="B"><block type="text"><field name="TEXT">aşağı</field></block></value></block></value><statement name="DO1"><block type="ai_sanal_imlec_sesle"><field name="YON">aşağı</field></block></statement><value name="IF2"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Ses</field></block></value><value name="B"><block type="text"><field name="TEXT">sol</field></block></value></block></value><statement name="DO2"><block type="ai_sanal_imlec_sesle"><field name="YON">sol</field></block></statement><value name="IF3"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Ses</field></block></value><value name="B"><block type="text"><field name="TEXT">sağ</field></block></value></block></value><statement name="DO3"><block type="ai_sanal_imlec_sesle"><field name="YON">sağ</field></block></statement></block></next></block></statement></block></next></block></xml>`,
        5: `<xml><variables><variable id="komut">Ses</variable></variables><block type="ai_metni_seslendir" x="50" y="50"><value name="TEXT"><block type="text"><field name="TEXT">Sesli fare asistanı aktif. Yön komutları verebilirsiniz.</field></block></value><next><block type="ai_sanal_imlec_ac"><next><block type="controls_whileUntil"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="komut">Ses</field><value name="VALUE"><block type="ai_ses_dinle"></block></value><next><block type="controls_if"><mutation elseif="4"></mutation><value name="IF0"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Ses</field></block></value><value name="B"><block type="text"><field name="TEXT">yukarı</field></block></value></block></value><statement name="DO0"><block type="ai_sanal_imlec_sesle"><field name="YON">yukarı</field></block></statement><value name="IF1"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Ses</field></block></value><value name="B"><block type="text"><field name="TEXT">aşağı</field></block></value></block></value><statement name="DO1"><block type="ai_sanal_imlec_sesle"><field name="YON">aşağı</field></block></statement><value name="IF2"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Ses</field></block></value><value name="B"><block type="text"><field name="TEXT">sol</field></block></value></block></value><statement name="DO2"><block type="ai_sanal_imlec_sesle"><field name="YON">sol</field></block></statement><value name="IF3"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Ses</field></block></value><value name="B"><block type="text"><field name="TEXT">sağ</field></block></value></block></value><statement name="DO3"><block type="ai_sanal_imlec_sesle"><field name="YON">sağ</field></block></statement><value name="IF4"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="komut">Ses</field></block></value><value name="B"><block type="text"><field name="TEXT">tıkla</field></block></value></block></value><statement name="DO4"><block type="ai_sanal_imlec_tikla"></block></statement></block></next></block></statement></block></next></block></next></block></xml>`
    },
    // DERS 14: SES SEVİYESİ
    14: {
        1: `<xml><block type="text_print" x="50" y="50"><value name="TEXT"><block type="ai_ses_seviyesi"></block></value></block></xml>`,
        2: `<xml><block type="controls_whileUntil" x="50" y="50"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="text_print"><value name="TEXT"><block type="ai_ses_seviyesi"></block></value><next><block type="ai_bekle"><field name="SECONDS">1</field></block></next></block></statement></block></xml>`,
        3: `<xml><variables><variable id="ses">Ses</variable></variables><block type="controls_whileUntil" x="50" y="50"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="ses">Ses</field><value name="VALUE"><block type="ai_ses_seviyesi"></block></value><next><block type="controls_if"><value name="IF0"><block type="logic_compare"><field name="OP">GT</field><value name="A"><block type="variables_get"><field name="VAR" id="ses">Ses</field></block></value><value name="B"><block type="math_number"><field name="NUM">60</field></block></value></block></value><statement name="DO0"><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Çok gürültülü!</field></block></value></block></statement><next><block type="ai_bekle"><field name="SECONDS">1</field></block></next></block></next></block></statement></block></xml>`,
        4: `<xml><variables><variable id="ses">Ses</variable></variables><block type="controls_whileUntil" x="50" y="50"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="ses">Ses</field><value name="VALUE"><block type="ai_ses_seviyesi"></block></value><next><block type="controls_if"><mutation else="1"></mutation><value name="IF0"><block type="logic_compare"><field name="OP">GT</field><value name="A"><block type="variables_get"><field name="VAR" id="ses">Ses</field></block></value><value name="B"><block type="math_number"><field name="NUM">50</field></block></value></block></value><statement name="DO0"><block type="ai_arkaplan_renk"><field name="COLOR">red</field></block></statement><statement name="ELSE"><block type="ai_arkaplan_renk"><field name="COLOR">green</field></block></statement><next><block type="ai_bekle"><field name="SECONDS">0.5</field></block></next></block></next></block></statement></block></xml>`,
        5: `<xml><variables><variable id="ses">Ses</variable></variables><block type="controls_whileUntil" x="50" y="50"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="ses">Ses</field><value name="VALUE"><block type="ai_ses_seviyesi"></block></value><next><block type="controls_if"><mutation elseif="1" else="1"></mutation><value name="IF0"><block type="logic_compare"><field name="OP">GT</field><value name="A"><block type="variables_get"><field name="VAR" id="ses">Ses</field></block></value><value name="B"><block type="math_number"><field name="NUM">60</field></block></value></block></value><statement name="DO0"><block type="ai_arkaplan_renk"><field name="COLOR">red</field><next><block type="text_print"><value name="TEXT"><block type="text"><field name="TEXT">Çok gürültülü! Lütfen sessiz olun.</field></block></value></block></next></block></statement><value name="IF1"><block type="logic_compare"><field name="OP">GT</field><value name="A"><block type="variables_get"><field name="VAR" id="ses">Ses</field></block></value><value name="B"><block type="math_number"><field name="NUM">30</field></block></value></block></value><statement name="DO1"><block type="ai_arkaplan_renk"><field name="COLOR">yellow</field></block></statement><statement name="ELSE"><block type="ai_arkaplan_renk"><field name="COLOR">green</field></block></statement><next><block type="ai_bekle"><field name="SECONDS">0.5</field></block></next></block></next></block></statement></block></xml>`
    },
    // DERS 15: PARMAK SAYMA
    15: {
        1: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"><next><block type="text_print"><value name="TEXT"><block type="ai_parmak_say"></block></value></block></next></block></next></block></xml>`,
        2: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="ai_parmak_say"></block></value></block></next></block></next></block></xml>`,
        3: `<xml><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"><next><block type="controls_whileUntil"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="text_print"><value name="TEXT"><block type="ai_parmak_say"></block></value><next><block type="ai_bekle"><field name="SECONDS">1</field></block></next></block></statement></block></next></block></next></block></xml>`,
        4: `<xml><variables><variable id="ps">Parmak</variable></variables><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"><next><block type="controls_whileUntil"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="ps">Parmak</field><value name="VALUE"><block type="ai_parmak_say"></block></value><next><block type="controls_if"><value name="IF0"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="ps">Parmak</field></block></value><value name="B"><block type="math_number"><field name="NUM">5</field></block></value></block></value><statement name="DO0"><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Çak bir beşlik!</field></block></value><next><block type="ai_bekle"><field name="SECONDS">3</field></block></next></block></statement></block></next></block></statement></block></next></block></next></block></xml>`,
        5: `<xml><variables><variable id="ps">ParmakSayısı</variable></variables><block type="ai_kamera_ac" x="50" y="50"><next><block type="ai_el_tespit_et"><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Parmaklarını kameraya göster!</field></block></value><next><block type="controls_whileUntil"><field name="MODE">WHILE</field><value name="BOOL"><block type="logic_boolean"><field name="BOOL">TRUE</field></block></value><statement name="DO"><block type="variables_set"><field name="VAR" id="ps">ParmakSayısı</field><value name="VALUE"><block type="ai_parmak_say"></block></value><next><block type="controls_if"><mutation elseif="1" else="1"></mutation><value name="IF0"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="ps">ParmakSayısı</field></block></value><value name="B"><block type="math_number"><field name="NUM">5</field></block></value></block></value><statement name="DO0"><block type="ai_arkaplan_renk"><field name="COLOR">green</field><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Çak bir beşlik!</field></block></value><next><block type="ai_bekle"><field name="SECONDS">3</field></block></next></block></next></block></statement><value name="IF1"><block type="logic_compare"><field name="OP">EQ</field><value name="A"><block type="variables_get"><field name="VAR" id="ps">ParmakSayısı</field></block></value><value name="B"><block type="math_number"><field name="NUM">2</field></block></value></block></value><statement name="DO1"><block type="ai_arkaplan_renk"><field name="COLOR">blue</field><next><block type="ai_metni_seslendir"><value name="TEXT"><block type="text"><field name="TEXT">Barış işareti! Kilit açıldı.</field></block></value><next><block type="ai_bekle"><field name="SECONDS">3</field></block></next></block></next></block></statement><statement name="ELSE"><block type="ai_arkaplan_renk"><field name="COLOR">black</field><next><block type="ai_bekle"><field name="SECONDS">0.2</field></block></next></block></statement></block></next></block></statement></block></next></block></next></block></next></block></xml>`
    }
};
